# site properties and page defaults
title: 金胡杨战队
subtitle: Golden Poplar Team
description: 坚韧不拔，胡杨不朽
header: images/background.jpg
header-video: images/JHY2026.mp4
footer: images/background.jpg
proofer: false
slogan: 坚韧不拔，胡杨不朽
# site social media and other links
links:
  email: lanjingzibumian@qq.com
  github: lanjingzibumian-ctrlDESCRIPTION=An engaging 1-3 sentence description of your lab.
  bilibili: "3546755463383730"
  qq: https://qun.qq.com/universal-share/share?ac=1&authKey=NoVToPoK4fTY2dm9WQRezVQ8tvPsXkVWB70idhelz2du0mCrxE%2B8C8Xzl0GBEZS%2B&busi_data=eyJncm91cENvZGUiOiIxMDM0MTEzNjkyIiwidG9rZW4iOiIrcUpyQnVWT0c1b3kyS2hGZXFuK0I4bkZQWHQ4Q0QrWmFLRHJZVml5cHNwelVWeWxaS0gzVW1HRkRPRlZQR1I4IiwidWluIjoiMjIxMjc1MzA5NSJ9&data=79t8_89royN5BTubbEa7-ZzZFDHZAA3o4UyzNTK4BwVsrEDn4P_ruo9kUCNMonmU1gkQy5G_PMO_lkYZRMNTTA&svctype=4&tempid=h5_group_info 
## jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  - scope:
      type: "awards"
    values:
      layout: award
  - scope:
      type: "events"
    values:  
      layout: event
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  - scope:
      type: "news"
    values:
      layout: post



collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true
  awards:
    output: true
  news:
    output: true
  projects:
    output: true
  patents:
    output: true
  events:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
